Repository 8-bend-inward/8_Seraphim, pull requests merged in 2023-09, with the labels that each got.

#8 [!HOTFIX] : 💥 중복 페이지 삭제
  app/src/main/java/com/example/contactproject/MyPageFragment.kt
  app/src/main/java/com/example/contactproject/MyPageFragmentAdapter.kt
Labels: bug

#11 [DESIGN] : 🎨 / Detailpage UI 구성
  app/src/main/res/drawable/call.png
  app/src/main/res/drawable/email.png
  app/src/main/res/drawable/gradation.xml
  app/src/main/res/drawable/layoutbackground_1.xml
  app/src/main/res/drawable/left.png
  app/src/main/res/layout/fragment_contact_detail.xml
Labels: UI

#12 UI/contact list
  app/src/main/java/com/android/contactproject/ContactListFragment.kt
  app/src/main/java/com/android/contactproject/ContactListFragmentAdapter.kt
  app/src/main/java/com/android/contactproject/UserDataModel.kt
  app/src/main/res/drawable-hdpi/heart.png
  app/src/main/res/layout/contact_list_item.xml
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: UI

#13 [LITTLE_FIX] : 🔧 UI 사이즈,스크롤 조정, MyDataClass 생성, 어댑터삭제
  app/src/main/java/com/android/contactproject/MainActivity.kt
  app/src/main/java/com/android/contactproject/MyPageData.kt
  app/src/main/java/com/android/contactproject/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: UI, feature

#14 [FEATURE] : AddContactDialog 기능 구현
  .idea/misc.xml
  app/src/main/java/com/android/contactproject/MainActivity.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: feature

#20 아이템 클릭 시 mypage로 데이터 전달
  .idea/misc.xml
  app/src/main/java/com/android/contactproject/ContactDetailFragment.kt
  app/src/main/java/com/android/contactproject/ContactDetailFragmentAdapter.kt
  app/src/main/java/com/android/contactproject/Favorites.kt
  app/src/main/java/com/android/contactproject/FavoritesAdapter.kt
  app/src/main/java/com/android/contactproject/MyPageFragment.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragment.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragmentAdapter.kt
  app/src/main/java/com/android/contactproject/contactlist/UserDataModel.kt
  app/src/main/res/drawable/painted_heart.png
  app/src/main/res/layout/activity_main.xml
Labels: feature

#23 [FEAT] : ⚙️ Favorites에서 bundle로데이터받고 넘겨주는거 까지 완료
  app/src/main/java/com/android/contactproject/Favorites.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragment.kt
Labels: feature

#25 [FEAT] : ⚙️ 플로팅버튼 이동, 이미지편집기능 구현
  app/src/main/java/com/android/contactproject/AddContactDialogFragment.kt
  app/src/main/java/com/android/contactproject/MainActivity.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/contact_list_fragment.xml
  app/src/main/res/layout/fragment_add_contact_dialog.xml
Labels: feature

#27 [FEAT] : ⚙️ Dialog에서 생성할때 데이터 리스트에저장후 contactList로 넘김 받아오는 로그까지 찍힘, 즐겨찾기기능 완료
  app/src/main/java/com/android/contactproject/AddContactDialogFragment.kt
  app/src/main/java/com/android/contactproject/AddMemberData.kt
  app/src/main/java/com/android/contactproject/Favorites.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragment.kt
Labels: feature

#28 [FEAT] : ⚙️[DESIGN] : 🎨 다이얼로그 UI변경, 조건추가,Accept버튼 눌렀을때 다이얼로그종료
  app/src/main/java/com/android/contactproject/AddContactDialogFragment.kt
  app/src/main/res/drawable/dialog_profile.xml
  app/src/main/res/layout/fragment_add_contact_dialog.xml
  app/src/main/res/values/colors.xml
Labels: feature, Design

#31 Ssu
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/contactproject/AddContactDialogFragment.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragment.kt
  app/src/main/java/com/android/contactproject/detailPage/ContactDetailActivity.kt
  app/src/main/java/com/android/contactproject/detailPage/ContactDetailFragment.kt
  app/src/main/res/drawable/bell.xml
  app/src/main/res/layout/activity_contact_detail.xml
Labels: Merge

#32 [MERGE] : ✅ main+devlop merge
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/contactproject/AddContactDialogFragment.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragment.kt
  app/src/main/res/drawable/bell.xml
Labels: Merge, Conflict

#34 [CONFLICT] : 💥🚚 conflict해결
  app/src/main/java/com/android/contactproject/AddContactDialogFragment.kt
  app/src/main/res/drawable/bell.xml
Labels: Merge, Conflict

#37 [FEAT] : ⚙️ Event Notification 구현 완료
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/contactproject/AddContactDialogFragment.kt
Labels: feature

#39 [FEAT] : ⚙️/[DESIGN] : 🎨 ContactList 뷰타입(Left&Right), UI변경/ Favorites 이름 오름차순정렬, UI변경
  app/src/main/java/com/android/contactproject/Favorites.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragmentAdapter.kt
  app/src/main/java/com/android/contactproject/contactlist/ViewType.kt
  app/src/main/res/layout/contact_list_item.xml
  app/src/main/res/layout/contact_list_item_type.xml
  app/src/main/res/layout/favorites_adapter.xml
Labels: UI, feature, Design

#41 [FEAT] : ⚙️ Favorites 팝업메뉴 선택에 따라서 리스트뷰,그리드뷰적용 완료
  app/src/main/java/com/android/contactproject/Favorites.kt
  app/src/main/java/com/android/contactproject/FavoritesAdapter.kt
  app/src/main/res/drawable/dots.png
  app/src/main/res/layout/fragment_favorites.xml
  app/src/main/res/layout/grid_type_item.xml
  app/src/main/res/menu/menu.xml
Labels: feature

#42 [FEAT] : ⚙️ ContactProfect : 하트 클릭 시 상단으로 이동
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragment.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragmentAdapter.kt
Labels: feature

#43 [BUG_FIX] : 🐛 즐겨찾기 중복 오류 해결
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragment.kt
  app/src/main/res/layout/activity_contact_detail.xml
Labels: bug

#44 [FEAT] : ⚙️ Favorites의 메뉴항목에 정렬방식 추가
  app/src/main/java/com/android/contactproject/Favorites.kt
  app/src/main/java/com/android/contactproject/FavoritesAdapter.kt
  app/src/main/res/menu/menu.xml
Labels: feature

#45 [FEAT] : ⚙️ 연락처 연동 기능 구현 완료
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/contactproject/AddContactDialogFragment.kt
  app/src/main/java/com/android/contactproject/MainActivity.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragment.kt
  app/src/main/java/com/android/contactproject/detailPage/ContactDetailActivity.kt
  app/src/main/res/layout/fragment_contact_detail.xml
Labels: feature

#49 Fix/design[DESIGN] : 🎨 전체적 디자인 약간 수정
  app/src/main/res/drawable/detail_box.xml
  app/src/main/res/drawable/man.png
  app/src/main/res/drawable/pencle.png
  app/src/main/res/layout/activity_add_contact_dialog.xml
  app/src/main/res/layout/activity_contact_detail.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/contact_list_item.xml
  app/src/main/res/layout/contact_list_item_type.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/mypage_revise_dialog.xml
  app/src/main/res/values/strings.xml
Labels: Design

#51 [FEAT] : ⚙️ 디테일페이지 전화버튼,메세지 버튼 클릭시 전화앱,메세지앱 구동가능
  app/src/main/java/com/android/contactproject/AddContactDialogFragment.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragment.kt
  app/src/main/java/com/android/contactproject/detailPage/ContactDetailActivity.kt
  app/src/main/res/layout/activity_contact_detail.xml
Labels: feature

#52 [DESIGN] : 🎨[CONFLICT] : 💥🚚 전체적인 UI수정/conflict해결
  app/src/main/java/com/android/contactproject/AddContactDialogFragment.kt
  app/src/main/java/com/android/contactproject/MainActivity.kt
  app/src/main/java/com/android/contactproject/MyPageFragment.kt
  app/src/main/java/com/android/contactproject/SwipeToCall.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragment.kt
  app/src/main/res/drawable/black_gray_gradation.png
  app/src/main/res/drawable/black_white_gradation.png
  app/src/main/res/drawable/changebtn.xml
  app/src/main/res/drawable/dialog_profile.xml
  app/src/main/res/drawable/dialogbtn.xml
  app/src/main/res/drawable/logo.png
  app/src/main/res/drawable/white_black_gradation.png
  app/src/main/res/layout/activity_add_contact_dialog.xml
  app/src/main/res/layout/appbar.xml
  app/src/main/res/layout/contact_list_fragment.xml
  app/src/main/res/layout/contact_list_item.xml
  app/src/main/res/layout/contact_list_item_type.xml
  app/src/main/res/layout/fragment_add_contact_dialog.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/mypage_revise_dialog.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
Labels: Design, Conflict

#53 [DESIGN] : 🎨 ItemType 임시수정
  app/src/main/res/layout/contact_list_item_type.xml
Labels: Design

#54 [DESIGN] : 🎨 MyPager의 상단 레이아웃 툴바로 통일
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragment.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragmentAdapter.kt
  app/src/main/res/layout/activity_contact_detail.xml
  app/src/main/res/layout/contact_list_fragment.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: feature

#55 [FEAT] : ⚙️ 다이얼로그 < - > contactList 데이터교환 완료
  app/src/main/java/com/android/contactproject/AddContactDialogFragment.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragment.kt
Labels: feature

#57 [!HOTFIX] : 💥 Swipe기능 충돌버그 해결
  app/src/main/java/com/android/contactproject/SwipeToCall.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragment.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragmentAdapter.kt
  app/src/main/res/layout/contact_list_item.xml
  app/src/main/res/layout/contact_list_item_type.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: bug

#58 [BUG_FIX] : 🐛 버그 수정 : initView 관련 주석처리(이거떄문에 정렬,그리드뷰,리스트뷰 다안됩니다.)
  .idea/misc.xml
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragment.kt
Labels: feature

#59 [DESIGN] : 🎨 디테일페이지 스크롤 영역 수정 완료
  app/src/main/res/layout/activity_contact_detail.xml
Labels: Design

#60 [FEAT] : ⚙️ 다이얼로그에서 만든 데이터 ContactListFragment 상단에 표시완료
  .idea/misc.xml
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragment.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListItemAdapter.kt
  app/src/main/res/layout/contact_list_fragment.xml
  app/src/main/res/layout/grid_type_item2.xml
Labels: feature

#61 [FEAT] : ⚙️ 스와이프기능, 디자인 제외 프로젝트 1차 완료
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragmentAdapter.kt
  app/src/main/res/drawable/dialogbtn.xml
  app/src/main/res/layout/contact_list_fragment.xml
  app/src/main/res/layout/contact_list_item.xml
  app/src/main/res/layout/contact_list_item_type.xml
  app/src/main/res/values/colors.xml
Labels: feature, Design

#62 [DESIGN] : 🎨 type별 배경색
  app/src/main/res/layout/contact_list_fragment.xml
  app/src/main/res/layout/contact_list_item_type.xml
  app/src/main/res/values/colors.xml
Labels: Design

#64 [BUG_FIX] : 🐛 즐겨찾기 버그 해결
  app/src/main/java/com/android/contactproject/Favorites.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragment.kt
Labels: bug

#65 [LITTLE_FIX] : 🔧 연락처 수정중
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragment.kt
  app/src/main/res/menu/menu.xml
Labels: question

#69 [BUG_FIX] : 🐛 다이얼로그 갤러리 픽스
  app/src/main/java/com/android/contactproject/AddContactDialogFragment.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragment.kt
Labels: bug

#70 Develop
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/contactproject/AddContactDialogFragment.kt
  app/src/main/java/com/android/contactproject/Favorites.kt
  app/src/main/java/com/android/contactproject/MainActivity.kt
  app/src/main/java/com/android/contactproject/MyPageFragment.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragment.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListFragmentAdapter.kt
  app/src/main/java/com/android/contactproject/contactlist/ContactListItemAdapter.kt
  app/src/main/java/com/android/contactproject/detailPage/ContactDetailActivity.kt
  app/src/main/res/drawable/jisu.png
  app/src/main/res/drawable/yunjeong.png
  app/src/main/res/layout/activity_contact_detail.xml
  app/src/main/res/layout/contact_list_fragment.xml
  app/src/main/res/layout/contact_list_item.xml
  app/src/main/res/layout/contact_list_item_type.xml
  app/src/main/res/layout/fragment_add_contact_dialog.xml
  app/src/main/res/layout/fragment_favorites.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/mypage_revise_dialog.xml
  app/src/main/res/menu/contactmenu.xml
  app/src/main/res/values/themes.xml
Labels: bug
